//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadanie1.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.IdContract = new HashSet<IdContract>();
        }
    
        public int IdOrder { get; set; }
        public int IdCustomer { get; set; }
        public int IdPerson { get; set; }
        public int IdBoat { get; set; }
        public int IdDetails { get; set; }
    
        public virtual Boat Boat { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdContract> IdContract { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual SalesPerson SalesPerson { get; set; }
    }
}
